version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: pokemons
      MYSQL_USER: drosa
      MYSQL_PASSWORD: ChangeMe
    ports:
      - "42333:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/pokemons?characterEncoding=UTF-8&useUnicode=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "ChangeMe"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
